name: xsdk_flutter_package
description: XFlutterPackage
version: 0.0.1
homepage: https://www.reabam.com

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

#https://pub.flutter-io.cn/
dependencies:
  flutter:
    sdk: flutter
  #多语言
  flutter_localizations:
    sdk: flutter

  #json
  json_annotation: ^4.7.0
  #网络请求框架 Dio http
  dio: ^4.0.6
  #WebSockets
  web_socket_channel: ^2.2.0
  #轻量级保存 android-SharePreference,ios/macOS-NSUserDefaults,Linux-In the XDG_DATA_HOME directory,Web-LocalStorage,Windows-In the roaming AppData directory
  shared_preferences: '^2.0.15'
  #图片加载(网络,缓存)
  cached_network_image: ^3.2.2
  #图片banners
  banner_carousel: ^1.2.1
  #生成uuid唯一码
  uuid: ^3.0.6
  #图片选择器
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  #json
  build_runner: ^2.3.3
  json_serializable: ^6.5.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # 添加素材
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
